	  var Tawk_API = Tawk_API || {}, Tawk_LoadStart = new Date(); (function () { var d = document.createElement("script"), c = document.getElementsByTagName("script")[0]; d.async = true; d.src = "https://embed.tawk.to/567e35602f19e3ec631e4e88/default"; d.charset = "UTF-8"; d.setAttribute("crossorigin", "*"); c.parentNode.insertBefore(d, c) })();
    
    
	$(document).ready(function () { $("#mymodal").on("hidden.bs.modal", function () { sessionStorage.setItem("showmsg", "2") }); if (sessionStorage.getItem("showmsg") == "1") { sessionStorage.setItem("showmsg", "2"); alert("Your Query Submitted Sucessfully ") } else { if (sessionStorage.getItem("showmsg") == "2") { } else { } } }); window.onscroll = function () { if (window.scrollY > 1000) { if (sessionStorage.getItem("showmsg") != "2") { $("#mymodal").modal("show") } } }; $("#mymodal").on("hidden.bs.modal", function () { sessionStorage.setItem("showmsg", "2") }); function loadenquiry() { $("#mymodal").modal("show") } window.onload = function () { $("img[lazy=1]").each(function () { $(this).attr("src", $(this).attr("data-src")), $("#quote-carousel").carousel({ pause: true, interval: 4000, }), $("#myCarousel1").carousel({ interval: 4000, }) }) };
    
	$(document).ready(function () { $('[data-toggle="popover"]').popover(); $("#serv1").fadeIn(3000); $("#placeid").fadeIn(4000); $("#clientid").fadeIn(5000); $("#testimonialid").fadeIn(6000); $("#technology").fadeIn(7000); $("#partnerid").fadeIn(8000); $("#strategyid").fadeIn(9000); $("#newslatterid").fadeIn(10000); $("#awardid").fadeIn(11000); $("#footerid").fadeIn(12000); $("#btnback").click(function () { $("#tops").scrollTop() }) });
    
	$(document).ready(function () { $(".man").click(function () { $(".classtab1").hide(); $(".classtab2").show() }); $(".man1").click(function () { $(".classtab1").show(); $(".classtab2").hide() }); $(".classtab2").css("display", "none") });
    
	
	$(document).ready(function () { $("#stz").click(function () { $(".alldropdiv").hide(); $(".stuzon").show() }); $("#closid").click(function () { $(".alldropdiv").hide(); $(".stuzon").hide() }); $("#serch").click(function () { $(".alldropdiv").hide(); $(".searchclass").show() }); $("#closid1").click(function () { $(".alldropdiv").hide(); $(".searchclass").hide() }); $("#plcmt").click(function () { $(".alldropdiv").hide(); $(".placement").show() }); $("#closid2").click(function () { $(".alldropdiv").hide(); $(".placement").hide() }); $("#evnt").click(function () { $(".alldropdiv").hide(); $(".enentclass").show() }); $("#closid3").click(function () { $(".alldropdiv").hide(); $(".enentclass").hide() }); $("#lng").click(function () { $(".alldropdiv").hide(); $(".languageclass").show() }); $("#closid4").click(function () { $(".alldropdiv").hide(); $(".languageclass").hide() }) });
    
	$(document).ready(function () { $("#pophov").hover(function () { $(".dio").slideDown(); $(".dio").animate({ width: "450px" }, "slow") }); $(".detailclass").mouseleave(function () { $(".dio").hide() }) });
    
	(function (d, e, j, h, f, c, b) { d.GoogleAnalyticsObject = f; d[f] = d[f] || function () { (d[f].q = d[f].q || []).push(arguments) }, d[f].l = 1 * new Date(); c = e.createElement(j), b = e.getElementsByTagName(j)[0]; c.async = 1; c.src = h; b.parentNode.insertBefore(c, b) })(window, document, "script", "https://www.google-analytics.com/analytics.js", "ga"); ga("create", "UA-38277732-1", "auto"); ga("send", "pageview");
    
	$(function () { $("#back-top").hide(); $(window).scroll(function () { if ($(this).scrollTop() > 100) { $("#back-top").fadeIn() } else { $("#back-top").fadeOut() } }); $("#back-top a").click(function () { $("body,html").animate({ scrollTop: 0 }, 800); return false }) });
